services:
  - type: web
    name: superbot
    env: python
    plan: starter
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: python bot.py
    pythonVersion: 3.11
    autoDeploy: true
